# Generated by Codex on 2026-05-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
