# Generated by Django 5.2.13 on 2026-05-09 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_message_edited_at_message_seen_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='completion_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
