# Generated by Django 5.2.13 on 2026-05-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_work_completion_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
