# Generated by Django 5.2.13 on 2026-05-10 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_work_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='work_report',
            field=models.TextField(blank=True, null=True),
        ),
    ]
