# Generated by Django 5.2.13 on 2026-05-10 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_work_work_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='work_report',
        ),
    ]
